model:
  arch: mini_gpt4_llama_v2
  model_type: pretrain_vicuna
  freeze_vit: True
  freeze_qformer: True
  max_txt_len: 512
  low_resource: False
  image_size: 224
  end_sym: "</s>"
  llama_model: "mistralai/Mistral-7B-Instruct-v0.2"
  
  ckpt: "checkpoints/video_mistral_checkpoint_best.pth" # set the checkpoint to start the training from
  
  chat_template: True
  lora_r: 64
  lora_alpha: 16
  length: 50
  use_grad_checkpoint_llm: True
  max_context_len: 4500 #7200
  device: "cuda:1"

datasets:
  engagenet: 
    batch_size: 1
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 200


run:
  task: image_text_pretrain
  seed: 42
  amp: True
  gpu: 1
  device: "cuda:1"