model:
  arch: mini_gpt4_llama_v2
  model_type: pretrain_vicuna
  freeze_vit: True
  freeze_qformer: True
  max_txt_len: 512 # 512
  low_resource: False
  image_size: 224
  end_sym: "</s>"
  llama_model: "mistralai/Mistral-7B-Instruct-v0.2"
  ckpt: "checkpoints/video_mistral_checkpoint_best.pth" # set the checkpoint to start the training from
  use_grad_checkpoint: True
  chat_template: True
  lora_r: 64
  lora_alpha: 16
  length: 50
  use_grad_checkpoint_llm: True
  max_context_len: 3600 # 7200
  # device: "cuda:1"

#replace this with your own dataset
datasets:
  engagenet: 
    batch_size: 1
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
      eval:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
      eval:
        name: "blip_caption"
    sample_ratio: 200


run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-4
  min_lr: 8e-5
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 8
  num_workers: 0 #16
  warmup_steps: 875
  iters_per_epoch: 875

  seed: 42
  output_dir: "training_output/engagenet/finetuned_mistral_engagenet"

  amp: True
  resume_ckpt_path: null

  evaluate: False
  train_splits: ["train"]
  valid_splits: ["eval"]
  test_splits: ["eval"]

  device: "cuda"
  # gpu: 0 # set DDP entry device
  world_size: 1
  dist_url: "env://"
  distributed: True
